feat: setup ALB and DNS
uw-ssec/post-disaster-comms pull request #107
Opened 2024-09-27 00:14 UTC by nikiburggraf

Pushed for testing (esp - pulling down an updated values.cloud.yaml), NOT ready for review and DON'T merge

todo:

* test
* undo userdata's checking out this branch specifically
* remove all EIP config stuff after testing

2024-10-10 23:46 UTC, nikiburggraf commented on deployment/cloud/aws/infrastructure/main.tf
> +    key    = "infrastructure/${local.neighborhood_lower}/${var.stage}/terraform.tfstate"
changed this up in case there were multiple neighborhoods running in the same account. This lets their tfstate files live in separate locations :)

2024-10-10 23:49 UTC, nikiburggraf commented on deployment/cloud/aws/infrastructure/modules/server/userdata
> +  - export HOME=/root
[this line](https://github.com/prefix-dev/pixi/blob/475ad6149cc01d6fdd507857dca58d500e1a0785/install/install.sh#L9) of Pixi's install script was failing to execute on the server without this, bc usually `$HOME` is not set during userdata/cloud-init execution. Set it while installing so Pixi could actually run

2024-10-10 23:49 UTC, nikiburggraf commented on deployment/cloud/aws/infrastructure/modules/server/userdata
> +  - unset HOME
and then thought "hmm, i wonder if this was unset for a reason? lemme just leave the environment the way i found it for the rest of the script"

2024-10-10 23:54 UTC, nikiburggraf commented
> > undo userdata's checking out this branch specifically
> 
> Just so you are aware, I think currently we still need to clone the repo so that the populate job can create the image.

yup, i just had to make it check out `main` instead before this was ready :) 

i needed to swap to this branch during testing so the server would pull and read from the correct values.cloud.yaml and make sure that that all worked, but I've put it back now that I'm done messing with everything

2024-10-11 16:23 UTC, lsetiawan commented on deployment/cloud/aws/account/main.tf
> +resource "aws_iam_policy" "tf_state_access" {
```suggestion
resource "aws_iam_policy" "this" {
```

2024-10-11 16:23 UTC, lsetiawan commented on deployment/cloud/aws/account/main.tf
> +resource "aws_iam_role_policy_attachment" "deploy_bucket_access" {
```suggestion
resource "aws_iam_role_policy_attachment" "this" {
```

2024-10-11 16:24 UTC, lsetiawan commented on deployment/cloud/aws/account/main.tf
> +resource "aws_iam_group_policy_attachment" "access_tf_state_bucket_group" {
```suggestion
resource "aws_iam_group_policy_attachment" "this" {
```

2024-10-11 16:30 UTC, lsetiawan requested changes
Thanks @nikiburggraf! This is looking good. Just a few small adjustments and I think we're ready to go. It's great to see you incorporated the opentofu format CLI to format the code. 😄

2024-10-11 16:32 UTC, nikiburggraf commented
Thanks @lsetiawan! Changes applied :)

2024-10-11 18:40 UTC, lsetiawan approved these changes
Thanks! This is now ready to go! :shipit:

2024-10-11 18:43 UTC, merged